### ISSUE TITLE
Nested Workflow executes indefinitely if DropPoint offline

### ISSUE THREAD

**Issue by shawncodewell** [Flowgear/feedback#1]
When you have a workflow that calls a nested workflow, and a droppoint required by the nested workflow is offline, the step in the nested workflow that uses the offline droppoint executes indefinitely.

**Comment by DanielChilcott** [comment]
This is an issue we've been attending to address for some time. Our plan is to add a DropPointOffline timeout property to the Connection property. The default value will be 0, indicating to wait indefinitely for the DropPoint to come online. Any value >= 0 will be the maximum timeout in seconds to wait before throwing an exception. Obviously the setting would only be applicable to invokes via a DropPoint.

Our intent was to only provide this on the V4 DroPoints. Would it be important to have it available on < V4 too?

**Comment by shawncodewell** [comment]
Yes v3 would be important as well.  Many enterprises are very slow to change to the latest operating systems, and as such there are still a LOT of pre-Windows Server 2012 servers out there, which require v3 droppoints.

**Comment by DanielChilcott** [comment]
This change has been rolled out to Community Pod and will be deployed to other production Pods over the next few days.

**Comment by DanielChilcott** [comment]
Also, it supports both legacy and current DropPoints
