### ISSUE TITLE
New Node Request - JMS/Stomp

### ISSUE THREAD

**Issue by gideon-io** [Flowgear/feedback#10]
A node that would allow for the submission and subscription to JMS/Stomp message queues and the acknowledgement of messages.

**Comment by DanielChilcott** [comment]
Could you provide some more information about the specific actions you might like to perform?

Would also be super useful if you could point us at SDK's for these services - preferably .NET based as we'd likely be building with them.

**Comment by gideon-io** [comment]
If we had to choose between implementing JMS or STOMP we would prefer STOMP.

More info is available here with some libraries for multiple languages: https://en.wikipedia.org/wiki/Streaming_Text_Oriented_Messaging_Protocol

We would like to be able to send messages to a queue and acknowledge specific messages.

**Comment by gideon-io** [comment]
This is no longer required.
