### ISSUE TITLE
Issues and Feedback on JSON Match Node

### ISSUE THREAD

**Issue by gideon-io** [Flowgear/feedback#11]
The current iteration of the JSON Match Node does not make working with JSON data as easy as it should be. For example, If a JSON array is passed into the JSON Match Node the following error occurs:

> Could not parse document: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.

This is an example of the JSON that is being passed into the Node:

`[{
	"data": {
		"project": "bla123",
		"domain": "testdomain.co.za",
		"competitors": ["tester.co.za", "tester.com"]
	},
	"method": "method_name"
}]`

When trying to access an object (essentially extracting an object from a larger object) this is the error:

> Failed to match property 'data': Can not convert Object to String.

When trying to access an array:

> Failed to match property 'data.competitors': Can not convert Array to String.

**Comment by gideon-io** [comment]
Additional to the above, when the Node errors out (when it can't match a property) it does not return any data at all. This happens even for valid properties, which renders the Node useless as a catch all for JSON that doesn't always have the same structure.

**Comment by SkillieZA** [comment]
@gideon-io 
I've made changes to the node to be able to return objects, arrays, and values. 

The Node should not throw an error anymore, unless a syntactically incorrect path is specified in the custom property, or if the JSON document is invalid. The node handles a case where the object a the path does not exist, it will just return nothing.

The latest version of the node is 1.0.0.3
