### ISSUE TITLE
BUG: Formatter expressions appear empty

### ISSUE THREAD

**Issue by gideon-io** [Flowgear/feedback#17]
Even though there is something in the formatter's expression, when attempting to edit the expression it appears to be empty. Tested on my.flowgear and my2.flowgear running on Chrome for Mac:

![image](https://cloud.githubusercontent.com/assets/7512362/19963109/aa1972f4-a1c3-11e6-86ab-358c6914d1ad.png)

![image](https://cloud.githubusercontent.com/assets/7512362/19963123/b6624d7e-a1c3-11e6-84f1-cbcea4de6331.png)

**Comment by DanielChilcott** [comment]
Thanks we've had another report of this but haven't been able to get a repro. Could you share a workflow that repro's the problem. At this point it looks like it might be something to do with the JSON content.

**Comment by gideon-io** [comment]
Sent you a mail.

**Comment by DanielChilcott** [comment]
Thanks, we've corrected the issue. Syntactically invalid JSON was preventing the text from displaying. A fix for this has been pushed to my2.flowgear.net. An update to my.flowgear.net will be done at 18:00UTC
