### ISSUE TITLE
New Node Request - JWT Node

### ISSUE THREAD

**Issue by chiehger** [Flowgear/feedback#20]
A node to generate a jwt with the HS256 algorithm. It should also be able to decode jwts that is being passed into it.

For more information you can view it here https://jwt.io/

**Comment by DanielChilcott** [comment]
This is a very specialised request but we would be happy to assist you in creating a connector for this purpose (https://developers.flowgear.net/kb/Building_Nodes). They do have a .NET nuget package so this shouldn't be difficult to create. If you would like us to assist, please share a GitHub repository with us and we'll create the Connector there for you (.NET project).

If you would prefer us to to build the Connector on a commercial basis, please reach out to us privately via support to request this (support@flowgear.net).
