### ISSUE TITLE
Enhancement - Ability to Specify Branch in Sage Evolution Node

### ISSUE THREAD

**Issue by figjamzim** [Flowgear/feedback#27]
We require the ability to deal with Branch Accounting using the Sage Evolution Node. Please could I request an enhancement to allow us to deal with Branch Accounting.

We need a way to be able to specify the Branch and for the Sage Evolution Node to work with Branch Accounting setups:

Reference:
http://developmentzone.pastel.co.za/index.php?title=C_Additional_Functionality

refers to:

*On a online branch accounting database a specific branch can be specified
as follows.*

DatabaseContext.SetBranchContext(1);

Some techincal detail:
We are still looking for a way to specify the branch in the XML order we place into your node..

We just need the right XML to pick the branch and we should be good.

From my reading this MAY have to be specified at a lower level (like in the Sage Evolution connector setup).. but I'm not sure how you've implemented this.

The actual errors we are seeing are the following:

1. Record (Customer: THR001C) cannot be used in this context as it is linked to branch 'CH'. Current branch is 'Global'. (referred to in original ticket)

2. Document 1: Value was either too large or too small for an Int32. (MORE PREVALENT) *this one we've tried various combinations of fields and values and we think we are missing a whole mandatory parameter*

for the latter error, the exact XML we pass to the node is:
<?xml version="1.0" encoding="utf-16"?>
<Documents xmlns="http://flowgear.net/Schemas/PastelEvolution/Documents.xsd">
  <Configuration>
    <DocumentType>ArSalesOrders</DocumentType>
    <ProcessAllOrNone>1</ProcessAllOrNone>
  </Configuration>
  <Document>
    <ProcessAction>Create</ProcessAction>
    <Account>GRO002F</Account>
    <ExternalOrderNo>123</ExternalOrderNo>
    <OrderNo>FMS_AT_ORD_001</OrderNo>
    <Description>Integration Testing</Description>
    <InvoiceTo>
      <Class>PO</Class>
    </InvoiceTo>
    <DeliverTo>
      <Class>PH</Class>
    </DeliverTo>
    <DetailLines>
      <DetailLine>
        <LineAction>Add</LineAction>
        <StockItem>FAT002</StockItem>
        <Quantity>6.0</Quantity>
        <Warehouse>F1H/FH</Warehouse>
      </DetailLine>
      <DetailLine>
        <LineAction>Add</LineAction>
        <StockItem>FXB001</StockItem>
        <Quantity>12.0</Quantity>
        <Warehouse>F1H/FH</Warehouse>
      </DetailLine>
      <DetailLine>
        <LineAction>Add</LineAction>
        <StockItem>FXT501</StockItem>
        <Quantity>13.0</Quantity>
        <Warehouse>F1H/FH</Warehouse>
      </DetailLine>
    </DetailLines>
  </Document>
</Documents>

NOTE we use the F1H/FH warehouse.. this is actually linked with the branch (which we cannot seem to specify).

To test this properly you may have to register the Sage Evolution Branch Accounting Module and test against an actual branch accounting setup. We are happy to test a dev version of the node for you against our Branch accounting setups.

**Comment by DanielChilcott** [comment]
Confirming that we will be providing support for branch accounting

**Comment by KGosebo** [comment]
Updated Sage Evolution node to support Branch accounting.
To test changes as client has provided URLs to integrations requiring change

**Comment by KGosebo** [comment]
Node changes tested successfully. Node to be deployed tomorrow 28 June after platform changes have been pushed to production
