### ISSUE TITLE
WHMCS support

### ISSUE THREAD

**Issue by SilverNodashi** [Flowgear/feedback#28]
Hi, 

Could you please add WHMCS support, in order to import invoices, customers, credit notes, etc into accounting applications like Sage One?

Thank you.

**Comment by DanielChilcott** [comment]
Hi,

We don't have immediate plans to support WHMCS with a Connector (Flowgear Node). However, we have previously developed integrations against it and would be happy to share these with you (they make use of our standard Web Request Node). If you're interested in that, please reach out to us via the Console chat.
