### ISSUE TITLE
Workflow Nodes sometimes jump to an incorrect position during a drag

### ISSUE THREAD

**Issue by DanielChilcott** [Flowgear/feedback#3]
During a drag operation, Workflow Nodes will occasionally stop tracking the cursor and end up placed in a seemingly random position. This location is often very far off-screen and makes it extremely difficult to locate them again.

**Comment by DanielChilcott** [comment]
Last week we pushed out a mitigation that restricted the maximum distance a Node should be able to jump. This has slightly mitigated the problem.

We have now re-worked the drag implementation and removed the JS library that we believe to have been causing a problem. This update will be pushed out as an experimental release to a secondary endpoint shortly.

**Comment by DanielChilcott** [comment]
We've pushed an update to https://my2.flowgear.net that we believe resolves the Node drag issue. There are currently no other changes in this build except for this fix.

If you've experienced this problem, please give us feedback to confirm you no longer have the issue and especially if you're still seeing it.

**Comment by vangroan** [comment]
I have tested on my2.flowgear.net and it appears to be resolved for me.
