### ISSUE TITLE
New Node Request - Validation Node

### ISSUE THREAD

**Issue by gideon-io** [Flowgear/feedback#4]
A node to handle validation scenarios. Some awesome scenarios that it could handle:
- Is input value defined
- Is input value a certain data type (boolean,string,integer etc.)

Ideas for other things the node could do can be found here: https://github.com/chriso/validator.js#validators

**Comment by gideon-io** [comment]
Hi, any update on creating this node? It would also help if it could validate XML and JSON and other document types...

**Comment by DanielChilcott** [comment]
Are you envisioning this as more of a platform feature where a set of validations can be enabled against workflow inputs (i.e. on the Variable Bar) or as a Node in its own right which will allow multiple inputs to be validated using the same rules?

Could you mock up a design example of how you see this playing out? Use the Formatter and add custom fields to denote the custom and new properties for the validation Node - that would be really helpful to understand what you're envisioning.

XML Validation should be done via the XML Validator Node (https://developers.flowgear.net/kb/Node:Xml_Validator). JSON at the moment can be validated with the same Node by simply prepending a JSON Convert in to switch JSON to XML for validation.

**Comment by gideon-io** [comment]
I would prefer it more as a Node that accepts inputs and allows you to specify the intended input type (String, Number, Decimal, Boolean, XML, JSON etc.) and if the input fails validation the Node errors out and the flow halts further execution. This will allow us to quickly ensure that the data we are receiving is valid depending on the input type we specify it to be validated as.

![image](https://cloud.githubusercontent.com/assets/7512362/19717632/df23b0c6-9b61-11e6-9d47-a702e28a13a9.png)

The screenshot above is a good example. The node accepts multiple inputs and using some sort of a dropdown allows the user to specify what type of data type to validate...

The XML Validator seems to require a schema for validation. I just want to validate that what I'm passing in is valid XML/JSON.

**Comment by DanielChilcott** [comment]
Ok we've put together a plan for this and should have an initial release in about 2 weeks

**Comment by gideon-io** [comment]
Myself and team are looking forward to it!

**Comment by DanielChilcott** [comment]
We've completed UI changes in the Console to support this feature. We'd now like to take a list of validations from you for a V1 release. Please send suggestions you'd like to see incorporated (I have looked at the link you referenced but need a smaller scope to start with).

**Comment by gideon-io** [comment]
Could we start with these 3 for now:
- Defined (checks if the value that is passed in is defined and not null)
- JSON (check if the value that is passed in is valid JSON)
- XML (check if the value that is passed in is valid XML)

Others that would be nice to have are:
- Boolean
- Integer
- Email
- Alpha
- Alphanumeric
- Date
- FQDN

**Comment by DanielChilcott** [comment]
Ok great, I have some of these already.

**Comment by gideon-io** [comment]
Awesome!

One thing I forgot to ask, do you know how the errors will work for the node?

Will the node process each input and error out when the input it is currently validating fails validation, or, will it attempt to validate all inputs and then error out indicating all the inputs that failed validation in the error message?

We are fine with whatever behaviour you use as long as the error message will indicate which input failed validation and for what reason. Eg. "Error: Unable to validate input 'json_object' as XML, validation failed." or something along these lines.

**Comment by DanielChilcott** [comment]
The Node will fire either a valid or an invalid output (same as how the if Node has a true and a false output).

There is also a report listing pass/fail for each specific test

**Comment by DanielChilcott** [comment]
Validate Node has been published. We've Obsoleted the old Validate Nodes (existing workflows that reference them are not impacted). Help at https://developers.flowgear.net/kb/Node:Validate
