### ISSUE TITLE
Enhancement/New Node - Object Notation to access XML/JSON data

### ISSUE THREAD

**Issue by gideon-io** [Flowgear/feedback#5]
This could be an enhancement to the XPath Match node or a new node altogether.

The node can accept either JSON or XML and the data that is passed in can be accessed using object notation instead of creating a schema.

Example input JSON:

`{
  "data": [
    {
      "project": "234hhsd",
      "domain": "dfgdfgh2.co.za",
      "user": {"id":"234h32h66","email":"gideon.vonmarschall@ignite.co.za"}
    }
  ],
  "method": "get_project"
}`

The user's ID could then be accessed like so: data[0].user.id

**Comment by DanielChilcott** [comment]
Planning for this Node has been completed. We expect to have an initial release within about a week.

**Comment by SkillieZA** [comment]
Created a node to match on Json keys in a json document. More details at [http://developers.flowgear.net/kb/Node:Json_Match](http://developers.flowgear.net/kb/Node:Json_Match)
