### ISSUE TITLE
"Drag to scroll" too sensitive in Design interface on Safari for Mac

### ISSUE THREAD

**Issue by gideon-io** [Flowgear/feedback#7]
When holding the mouse button down and drag the mouse to move around the interface the action seems to be too sensitive making it difficult to move around the interface. Tested with touchpad, a regular mouse, and a magic mouse.

**Comment by DanielChilcott** [comment]
If you drag a Node does this exhibit the same sensitivity problem or is it just a drag of the canvas that's a problem? Also, has this issue just started or have you not used a Mac/Safari previously?

**Comment by gideon-io** [comment]
@DanielChilcott strangely the interface cannot be interacted with at all. I can't move any nodes, I can't modify the IO points, etc.

**Comment by DanielChilcott** [comment]
We're addressing this as part of a larger issue to deal with compatibility with Safari. The primary affected area is the workflow designer and it affects Safari in iOS too.

The canvas drag issue has been resolved, start tuned for updates on other types of interaction with the workflow!

**Comment by gideon-io** [comment]
Thanks @DanielChilcott . Not sure if this issue is the right place but I can't copy workflows using Safari for Mac either. I can select the workflows I want to copy but the UI buttons seem to do nothing...

**Comment by DanielChilcott** [comment]
Safari issues should now be resolved. This includes Mac OS and iOS.
