### ISSUE TITLE
Enhancement - More descriptive window titles

### ISSUE THREAD

**Issue by gideon-io** [Flowgear/feedback#8]
It's difficult to manage more than one tab with Flowgear as it seems the titles are always "Flowgear", please could you use the flow name as the HTML title when in the design view of a flow.

![image](https://cloud.githubusercontent.com/assets/7512362/17521105/5c883fde-5e52-11e6-9421-2fbb89519a73.png)

**Comment by DanielChilcott** [comment]
Great suggestion - we've been intending to do this for a while.

**Comment by DanielChilcott** [comment]
Window tabs now share the same title as the Pane title.
