### ISSUE TITLE
Bug/Enhancement - Web Request node errors out when HTTP response status in certain range

### ISSUE THREAD

**Issue by gideon-io** [Flowgear/feedback#9]
It seems as though the Web Request node errors out without exposing the response body and status when a response with a 400 or 500 is returned (perhaps other status codes aswell, haven't tested).

eg.:
![image](https://cloud.githubusercontent.com/assets/7512362/17626899/88471ef6-60af-11e6-94fc-aebca46a9c0b.png)

**Comment by DanielChilcott** [comment]
The default behaviour on a non-200 response is to throw an exception. If you want to get at the error response data, create a connection and set AlwaysReturnResponse in the connection to True. 

See http://developers.flowgear.net/kb/Node:Web_Request
